// Static capability-pack manifests (host · L1 skills).
// This catalog is descriptive only: it does not download, install, or execute packs.
import type { CapabilityPackManifest } from './capability-pack-governance.js';

export const CAPABILITY_PACK_CATALOG: readonly CapabilityPackManifest[] = Object.freeze([
  {
    schemaVersion: 'agent-cowork.pack.v1',
    id: 'core-text-pack',
    name: 'Core Text Pack',
    version: '0.1.0',
    description: 'Markdown、TXT、JSON、CSV 等基础本地文本处理能力,随主包可用。',
    category: 'capability',
    publisher: 'Agent Cowork',
    license: 'internal',
    capabilities: ['text.read', 'markdown.write', 'json.read', 'csv.read'],
    dependencyIds: ['node', 'sqlite'],
    requiredPackIds: [],
    recommendedForRoles: ['developer', 'pm', 'legal', 'finance', 'hr', 'sales', 'design'],
    permissions: [{ kind: 'filesystem', scope: 'trustedRoot', reason: '读取和写入用户批准的工作区文件。', default: 'ask' }],
    installMode: 'bundled',
    security: { signed: true, sandboxRequired: false, networkDuringRuntime: 'none' },
  },
  {
    schemaVersion: 'agent-cowork.pack.v1',
    id: 'browser-automation-pack',
    name: 'Browser Automation Pack',
    version: '0.1.0',
    description: '按需补齐 Chromium 截图、网页交互 smoke 与前端视觉验收能力。',
    category: 'capability',
    publisher: 'Agent Cowork',
    license: 'internal',
    capabilities: ['browser.screenshot', 'web.smoke', 'ui.visual-check'],
    dependencyIds: ['playwright-chromium'],
    requiredPackIds: [],
    recommendedForRoles: ['developer', 'design', 'pm'],
    permissions: [{ kind: 'shell', scope: 'local-browser', reason: '启动本地浏览器执行截图和 smoke。', default: 'ask' }],
    installMode: 'plan-only',
    security: { signed: false, sandboxRequired: false, networkDuringRuntime: 'ask' },
  },
  {
    schemaVersion: 'agent-cowork.pack.v1',
    id: 'frontend-design-pack',
    name: 'Frontend Design Pack',
    version: '0.1.0',
    description: '前端 UI 编码的 design brief、组件扫描、静态审查与可选截图验收。',
    category: 'design',
    publisher: 'Agent Cowork',
    license: 'internal',
    capabilities: ['design.brief', 'design.static-review', 'design.visual-smoke'],
    dependencyIds: ['playwright-chromium'],
    requiredPackIds: ['browser-automation-pack'],
    recommendedForRoles: ['developer', 'design'],
    permissions: [
      { kind: 'filesystem', scope: 'trustedRoot', reason: '读取组件和样式以生成设计上下文。', default: 'ask' },
      { kind: 'shell', scope: 'local-browser', reason: '可选启动本地浏览器生成截图。', default: 'ask' },
    ],
    installMode: 'plan-only',
    security: { signed: false, sandboxRequired: false, networkDuringRuntime: 'ask' },
  },
  {
    schemaVersion: 'agent-cowork.pack.v1',
    id: 'pdf-ocr-pack',
    name: 'PDF OCR Pack',
    version: '0.1.0',
    description: '扫描件 PDF 和图片文字识别能力;缺失时应降级为文本页摘要。',
    category: 'capability',
    publisher: 'Agent Cowork',
    license: 'internal',
    capabilities: ['pdf.read', 'ocr.scan'],
    dependencyIds: ['tesseract-ocr', 'pandoc'],
    requiredPackIds: [],
    recommendedForRoles: ['legal', 'finance', 'hr', 'pm'],
    permissions: [{ kind: 'filesystem', scope: 'trustedRoot', reason: '读取用户选择的 PDF/图片文件。', default: 'ask' }],
    installMode: 'plan-only',
    security: { signed: false, sandboxRequired: false, networkDuringRuntime: 'none' },
  },
  {
    schemaVersion: 'agent-cowork.pack.v1',
    id: 'data-analysis-pack',
    name: 'Data Analysis Pack',
    version: '0.1.0',
    description: 'CSV、Excel、统计和本地数据分析增强能力。',
    category: 'capability',
    publisher: 'Agent Cowork',
    license: 'internal',
    capabilities: ['data.profile', 'data.analyze', 'chart.write'],
    dependencyIds: ['data-science'],
    requiredPackIds: [],
    recommendedForRoles: ['finance', 'developer', 'pm'],
    permissions: [{ kind: 'filesystem', scope: 'trustedRoot', reason: '读取用户批准的数据文件并写入产物。', default: 'ask' }],
    installMode: 'plan-only',
    security: { signed: false, sandboxRequired: true, networkDuringRuntime: 'none' },
  },
  {
    schemaVersion: 'agent-cowork.pack.v1',
    id: 'developer-role-pack',
    name: 'Developer Role Pack',
    version: '0.1.0',
    description: '开发者岗位推荐包:代码理解、Git、浏览器验收和前端设计审查。',
    category: 'role',
    publisher: 'Agent Cowork',
    license: 'internal',
    capabilities: ['role.developer'],
    dependencyIds: ['mingit', 'playwright-chromium'],
    requiredPackIds: ['frontend-design-pack'],
    recommendedForRoles: ['developer'],
    permissions: [
      { kind: 'filesystem', scope: 'trustedRoot', reason: '读取代码仓库和写入用户批准的补丁。', default: 'ask' },
      { kind: 'shell', scope: 'git', reason: '运行只读 Git 检查或用户批准的仓库命令。', default: 'ask' },
    ],
    installMode: 'plan-only',
    security: { signed: false, sandboxRequired: true, networkDuringRuntime: 'ask' },
  },
]);
