// Model provider catalog data(host · L1 domain · engine/provider)
// ---------------------------------------------------------------------------
// 22 个厂商的 provider/model 目录数据。类型定义见 catalog.ts;从其拆出以满足文件大小门禁。
import type { ProviderCatalogEntry } from './catalog-types.js';

export const MODEL_PROVIDER_CATALOG = [
  {
    id: 'kimi-api',
    displayName: 'Kimi / Moonshot',
    aliases: ['kimi', 'moonshot', 'moonshot-kimi'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.moonshot.ai/v1',
    defaultModel: 'kimi-k2.7-code',
    models: ['kimi-k2.7-code', 'kimi-k2.7-code-highspeed', 'kimi-k2-0905-preview', 'kimi-k2.6', 'kimi-k2.5'],
    apiKeyEnv: ['KIMI_API_KEY', 'MOONSHOT_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    aliases: ['deepseek-cn'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.deepseek.com',
    defaultModel: 'deepseek-v4-flash',
    models: ['deepseek-v4-flash', 'deepseek-v4-pro'],
    apiKeyEnv: ['DEEPSEEK_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'qwen-dashscope-cn',
    displayName: 'Qwen / DashScope',
    aliases: ['qwen', 'dashscope', 'aliyun-qwen', 'tongyi'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModel: 'qwen3.7-plus',
    models: ['qwen2-5-math-72b-instruct', 'deepseek-r1-0528', 'qwen3-omni-flash', 'deepseek-v4-flash', 'qwen-plus', 'qwen3-coder-30b-a3b-instruct', 'qwen2-5-coder-7b-instruct', 'deepseek-v3', 'qwen3-omni-flash-realtime', 'deepseek-r1-distill-llama-70b', 'qwen3-32b', 'qwen-omni-turbo-realtime', 'qwen2-5-math-7b-instruct', 'qwen3-next-80b-a3b-instruct', 'qwen3.7-plus', 'qwen3.7-max', 'qwen-long', 'qwen-math-turbo', 'qwen3-max', 'qwen2-5-omni-7b', 'qwen3-8b', 'qwen2-5-14b-instruct', 'glm-5.1', 'deepseek-v4-pro', 'qwen3-next-80b-a3b-thinking', 'qvq-max', 'qwen-plus-character', 'qwen3.5-flash', 'qwen3.6-flash', 'qwen2-5-vl-72b-instruct', 'qwen3-vl-plus', 'qwen-vl-ocr', 'qwen-mt-turbo', 'qwen-math-plus', 'qwen-mt-plus', 'qwen3.5-plus', 'qwen-omni-turbo', 'qwen2-5-72b-instruct', 'deepseek-r1-distill-qwen-7b', 'deepseek-v3-1', 'qwen2-5-coder-32b-instruct', 'qwen-flash', 'deepseek-v3-2-exp', 'moonshot-kimi-k2-instruct', 'deepseek-r1-distill-qwen-14b', 'qwen3-vl-235b-a22b', 'qwen-deep-research', 'kimi-k2.5', 'qwen3-vl-30b-a3b', 'qwen-vl-max', 'deepseek-r1-distill-qwen-1-5b', 'qwen-max', 'MiniMax-M2.5', 'qwen3-235b-a22b', 'deepseek-r1-distill-llama-8b', 'kimi-k2.6', 'qwen3-coder-480b-a35b-instruct', 'qwq-plus', 'qwen2-5-32b-instruct', 'qwen3.5-397b-a17b', 'tongyi-intent-detect-v3', 'qwen3-coder-flash', 'deepseek-r1-distill-qwen-32b', 'qwq-32b', 'qwen3-14b', 'qwen3-asr-flash', 'qwen-doc-turbo', 'glm-5', 'qwen-turbo', 'qwen2-5-7b-instruct', 'qwen2-5-vl-7b-instruct', 'qwen3.6-max-preview', 'qwen-vl-plus', 'qwen3.6-plus', 'MiniMax/MiniMax-M2.7', 'kimi/kimi-k2.5', 'siliconflow/deepseek-r1-0528', 'siliconflow/deepseek-v3.1-terminus', 'siliconflow/deepseek-v3-0324', 'siliconflow/deepseek-v3.2', 'qwen3-coder-plus'],
    apiKeyEnv: ['DASHSCOPE_API_KEY', 'QWEN_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'zai-glm',
    displayName: 'Z.ai / GLM',
    aliases: ['zhipu', 'glm', 'bigmodel'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.z.ai/api/paas/v4',
    defaultModel: 'glm-5.2',
    models: ['glm-5.1', 'glm-5.2', 'glm-5v-turbo', 'glm-5', 'glm-4.5-flash', 'glm-4.7-flash', 'glm-4.5-air', 'glm-4.6v', 'glm-4.6', 'glm-4.7-flashx', 'glm-4.5', 'glm-4.5v', 'glm-4.7'],
    apiKeyEnv: ['ZAI_API_KEY', 'ZHIPUAI_API_KEY', 'BIGMODEL_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'volcengine-ark',
    displayName: 'Volcengine Ark',
    aliases: ['ark', 'doubao', 'volcengine'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    defaultModel: 'doubao-seed-1-6',
    models: ['doubao-seed-1-6', 'doubao-1-5-pro-32k', 'doubao-1-5-lite-32k'],
    apiKeyEnv: ['ARK_API_KEY', 'VOLCENGINE_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'baidu-qianfan',
    displayName: 'Baidu Qianfan',
    aliases: ['qianfan', 'wenxin', 'ernie'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
    defaultModel: 'ernie-4.5-turbo',
    models: ['ernie-4.5-turbo', 'ernie-4.0-turbo-8k', 'ernie-speed-8k'],
    apiKeyEnv: ['QIANFAN_API_KEY', 'BAIDU_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'tencent-hunyuan',
    displayName: 'Tencent Hunyuan',
    aliases: ['hunyuan', 'tencent'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    defaultModel: 'hunyuan-turbos-latest',
    models: ['hunyuan-turbos-latest', 'hunyuan-large', 'hunyuan-standard'],
    apiKeyEnv: ['HUNYUAN_API_KEY', 'TENCENT_HUNYUAN_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'minimax',
    displayName: 'MiniMax',
    aliases: ['minimax-cn'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.minimaxi.com/v1',
    defaultModel: 'MiniMax-M2.7',
    models: ['MiniMax-M2.1', 'MiniMax-M2.5-highspeed', 'MiniMax-M2.7-highspeed', 'MiniMax-M2', 'MiniMax-M2.5', 'MiniMax-M3', 'MiniMax-M2.7'],
    apiKeyEnv: ['MINIMAX_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'iflytek-spark',
    displayName: 'iFlytek Spark',
    aliases: ['spark', 'xinghuo', 'iflytek'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://spark-api-open.xf-yun.com/v1',
    defaultModel: 'spark-max',
    models: ['spark-max', 'spark-pro', 'spark-lite'],
    apiKeyEnv: ['SPARK_API_KEY', 'XFYUN_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'siliconflow-cn',
    displayName: 'SiliconFlow',
    aliases: ['siliconflow'],
    region: 'cn',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    defaultModel: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    models: ['baidu/ERNIE-4.5-300B-A47B', 'ByteDance-Seed/Seed-OSS-36B-Instruct', 'stepfun-ai/Step-3.5-Flash', 'inclusionAI/Ling-flash-2.0', 'Pro/moonshotai/Kimi-K2.6', 'Pro/moonshotai/Kimi-K2.5', 'Pro/zai-org/GLM-5', 'Pro/zai-org/GLM-5.1', 'Pro/deepseek-ai/DeepSeek-R1', 'Pro/deepseek-ai/DeepSeek-V3.1-Terminus', 'Pro/deepseek-ai/DeepSeek-V3.2', 'Pro/deepseek-ai/DeepSeek-V3', 'Pro/MiniMaxAI/MiniMax-M2.5', 'Qwen/Qwen3.6-35B-A3B', 'Qwen/Qwen3.5-397B-A17B', 'Qwen/Qwen3-235B-A22B-Thinking-2507', 'Qwen/Qwen3.5-122B-A10B', 'Qwen/Qwen3.5-27B', 'Qwen/Qwen3-8B', 'Qwen/Qwen3.5-4B', 'Qwen/Qwen3.5-9B', 'Qwen/Qwen3-32B', 'Qwen/Qwen3-14B', 'Qwen/Qwen3.5-35B-A3B', 'Qwen/Qwen3-VL-32B-Thinking', 'Qwen/Qwen3-VL-30B-A3B-Instruct', 'Qwen/Qwen2.5-72B-Instruct', 'Qwen/Qwen3-VL-32B-Instruct', 'Qwen/Qwen3-VL-235B-A22B-Thinking', 'Qwen/Qwen3-VL-8B-Instruct', 'Qwen/Qwen3-VL-30B-A3B-Thinking', 'Qwen/Qwen3-30B-A3B-Instruct-2507', 'Qwen/Qwen3-Coder-30B-A3B-Instruct', 'Qwen/Qwen3-Coder-480B-A35B-Instruct', 'Qwen/Qwen3-VL-235B-A22B-Instruct', 'Qwen/Qwen2.5-7B-Instruct', 'PaddlePaddle/PaddleOCR-VL-1.5', 'tencent/Hunyuan-A13B-Instruct', 'zai-org/GLM-5.2', 'zai-org/GLM-4.5-Air', 'deepseek-ai/DeepSeek-R1', 'deepseek-ai/DeepSeek-V3.1-Terminus', 'deepseek-ai/DeepSeek-V4-Flash', 'deepseek-ai/DeepSeek-V4-Pro', 'deepseek-ai/DeepSeek-V3.2', 'deepseek-ai/DeepSeek-OCR', 'deepseek-ai/DeepSeek-V3'],
    apiKeyEnv: ['SILICONFLOW_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'openai',
    displayName: 'OpenAI',
    aliases: ['openai-compatible'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-5.5',
    models: ['gpt-5.5', 'gpt-5.5-pro', 'gpt-image-2', 'gpt-5.3-codex', 'gpt-5.3-codex-spark', 'gpt-5-codex', 'gpt-5.4', 'gpt-5.4-pro', 'gpt-5.4-mini', 'gpt-5.4-nano', 'gpt-5.3-chat-latest', 'gpt-5.1', 'gpt-5.1-codex', 'gpt-5.1-codex-max', 'gpt-5.1-codex-mini', 'gpt-5.1-chat-latest', 'gpt-5', 'gpt-5-mini', 'gpt-5-nano', 'gpt-5-chat-latest', 'o3', 'o3-pro', 'o3-mini', 'o4-mini', 'o4-mini-deep-research', 'o3-deep-research', 'gpt-4o', 'gpt-4o-mini', 'gpt-4o-2024-11-20', 'gpt-4o-2024-08-06', 'gpt-4o-2024-05-13', 'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'gpt-4-turbo', 'gpt-4', 'o1', 'o1-pro', 'chatgpt-image-latest', 'text-embedding-3-large', 'text-embedding-3-small', 'text-embedding-ada-002', 'gpt-3.5-turbo'],
    apiKeyEnv: ['OPENAI_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'anthropic',
    displayName: 'Anthropic Claude',
    aliases: ['claude'],
    region: 'global',
    protocol: 'anthropic-messages',
    defaultBaseUrl: 'https://api.anthropic.com/v1',
    defaultModel: 'claude-sonnet-5',
    models: ['claude-sonnet-5', 'claude-opus-4-8', 'claude-haiku-4-5', 'claude-fable-5', 'claude-sonnet-4-6', 'claude-opus-4-7', 'claude-opus-4-6', 'claude-opus-4-5', 'claude-opus-4-5-20251101', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-5', 'claude-sonnet-4-5-20250929', 'claude-sonnet-4-20250514', 'claude-sonnet-4-0', 'claude-opus-4-20250514', 'claude-opus-4-1', 'claude-opus-4-1-20250805', 'claude-opus-4-0', 'claude-3-7-sonnet-20250219', 'claude-3-5-sonnet-20241022', 'claude-3-5-sonnet-20240620', 'claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307'],
    apiKeyEnv: ['ANTHROPIC_API_KEY', 'CLAUDE_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'google',
    displayName: 'Google Gemini',
    aliases: ['gemini', 'google-ai', 'google-generative-ai'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    defaultModel: 'gemini-3.5-flash',
    models: ['gemini-3.5-flash', 'gemini-3.1-pro-preview', 'gemini-3.1-flash-lite', 'gemini-3-flash-preview', 'gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.0-flash', 'gemini-2.0-flash-lite'],
    apiKeyEnv: ['GEMINI_API_KEY', 'GOOGLE_API_KEY', 'GOOGLE_GENERATIVE_AI_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'xai',
    displayName: 'xAI Grok',
    aliases: ['grok', 'x-ai'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.x.ai/v1',
    defaultModel: 'grok-4.3',
    models: ['grok-4.3', 'grok-build-0.1'],
    apiKeyEnv: ['XAI_API_KEY', 'GROK_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'groq',
    displayName: 'Groq',
    aliases: ['groqcloud'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b', 'qwen/qwen3-32b', 'meta-llama/llama-4-scout-17b-16e-instruct', 'groq/compound', 'groq/compound-mini'],
    apiKeyEnv: ['GROQ_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'mistral',
    displayName: 'Mistral',
    aliases: ['mistralai', 'mistral-ai'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'mistral-large-latest',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest', 'devstral-medium-latest', 'devstral-small-2507', 'ministral-8b-latest', 'ministral-3b-latest', 'magistral-medium-latest', 'magistral-small', 'pixtral-large-latest'],
    apiKeyEnv: ['MISTRAL_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'openrouter',
    displayName: 'OpenRouter',
    aliases: ['open-router'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'anthropic/claude-sonnet-5',
    models: ['anthropic/claude-sonnet-5', 'anthropic/claude-opus-4.8', 'openai/gpt-5.5', 'google/gemini-3.5-flash', 'google/gemini-3.1-pro-preview', 'deepseek/deepseek-v4-pro', 'deepseek/deepseek-v4-flash', 'meta-llama/llama-3.3-70b-instruct', 'x-ai/grok-4.3', 'x-ai/grok-4.20', 'qwen/qwen3-max', 'minimax/minimax-m2', 'z-ai/glm-5.2', 'moonshotai/kimi-k2.6', 'mistralai/mistral-large-2512'],
    apiKeyEnv: ['OPENROUTER_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'perplexity',
    displayName: 'Perplexity',
    aliases: ['pplx', 'sonar'],
    region: 'global',
    protocol: 'openai-chat',
    defaultBaseUrl: 'https://api.perplexity.ai',
    defaultModel: 'sonar-pro',
    models: ['sonar-pro', 'sonar', 'sonar-reasoning-pro', 'sonar-deep-research'],
    apiKeyEnv: ['PERPLEXITY_API_KEY', 'PPLX_API_KEY'],
    requiresApiKey: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'ollama',
    displayName: 'Ollama',
    aliases: ['ollama-local', 'local-ollama'],
    region: 'local',
    protocol: 'openai-chat',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: 'qwen3',
    models: ['qwen3', 'qwen3-coder', 'qwen2.5:7b', 'qwen2.5:3b', 'qwen2.5:1.5b', 'qwen2.5:0.5b', 'deepseek-r1:7b', 'ibm/granite3.3:2b', 'lfm2.5-thinking:1.2b', 'qwen2.5vl:7b', 'minicpm-v4.5:latest', 'bge-m3:latest'],
    apiKeyEnv: [],
    requiresApiKey: false,
    allowCustomBaseUrl: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'openai/local',
    displayName: 'Local OpenAI-compatible',
    aliases: ['local-openai', 'local', 'local-openai-compatible'],
    region: 'local',
    protocol: 'openai-chat',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: 'qwen3',
    models: ['qwen3', 'qwen3-coder', 'qwen2.5:7b', 'qwen2.5:3b', 'qwen2.5:1.5b', 'qwen2.5:0.5b', 'deepseek-r1:7b', 'local-model'],
    apiKeyEnv: [],
    requiresApiKey: false,
    allowCustomBaseUrl: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'lmstudio',
    displayName: 'LM Studio',
    aliases: ['lm-studio', 'local-lmstudio'],
    region: 'local',
    protocol: 'openai-chat',
    defaultBaseUrl: 'http://127.0.0.1:1234/v1',
    defaultModel: 'local-model',
    models: ['local-model', 'qwen3', 'qwen3-coder', 'deepseek-r1', 'llama-3.1-8b-instruct', 'gpt-oss-20b'],
    apiKeyEnv: [],
    requiresApiKey: false,
    allowCustomBaseUrl: true,
    allowCustomModel: true,
    source: 'builtin',
  },
  {
    id: 'custom-openai-compatible',
    displayName: 'Custom OpenAI-compatible',
    aliases: ['custom-openai', 'customer-gateway', 'enterprise-gateway'],
    region: 'custom',
    protocol: 'openai-chat',
    defaultBaseUrl: '',
    defaultModel: '',
    models: ['custom-model'],
    apiKeyEnv: ['CUSTOM_OPENAI_API_KEY', 'MODEL_API_KEY'],
    requiresApiKey: false,
    allowCustomBaseUrl: true,
    allowCustomModel: true,
    baseUrlRequired: true,
    source: 'builtin',
  },
] as const satisfies readonly ProviderCatalogEntry[];
