import type { OrchestrationRecipe } from '../workflow-types.js';

export const officeTeamRecipe: OrchestrationRecipe = {
  id: 'office-team',
  displayName: 'Office team handoff',
  mode: 'handoff',
  agents: ['excel_helper', 'word_polisher', 'ppt_designer', 'file_organizer', 'verifier', 'security_reviewer'],
  steps: [
    {
      id: 'profile_inputs',
      kind: 'agent_task',
      agentId: 'excel_helper',
      title: 'Profile source materials',
      instruction: 'Inspect the supplied office or data context and summarize tables, figures, and missing fields.',
      expectedOutput: 'Input profile with data-quality notes.',
      handoff: { reason: 'Supervisor assigns the source-profile stage before document and deck work.' },
    },
    {
      id: 'polish_doc',
      kind: 'agent_task',
      agentId: 'word_polisher',
      title: 'Polish document brief',
      instruction: 'Turn the source context into a clear document brief with tone and structure notes.',
      expectedOutput: 'Document brief and wording improvements.',
      dependencies: ['profile_inputs'],
      handoff: { reason: 'Input profile is ready for document wording and structure.' },
    },
    {
      id: 'outline_deck',
      kind: 'agent_task',
      agentId: 'ppt_designer',
      title: 'Outline presentation',
      instruction: 'Create a slide outline from the profile and document brief, including chart or visual suggestions.',
      expectedOutput: 'Presentation outline with slide-level bullets.',
      dependencies: ['profile_inputs', 'polish_doc'],
      handoff: { reason: 'Profile and document brief are ready for slide outlining.' },
    },
    {
      id: 'organize_files',
      kind: 'agent_task',
      agentId: 'file_organizer',
      title: 'Plan file organization',
      instruction: 'Suggest a non-mutating file organization plan for the source materials.',
      expectedOutput: 'Read-only file organization preview.',
      dependencies: ['profile_inputs'],
      handoff: { reason: 'Input profile is ready for a read-only file organization plan.' },
    },
    {
      id: 'verify_office_handoff',
      kind: 'agent_task',
      agentId: 'verifier',
      title: 'Verify office handoff',
      instruction: 'Check that document, deck, and file organization outputs are complete and grounded.',
      expectedOutput: 'Verification result with warnings.',
      dependencies: ['outline_deck', 'organize_files'],
      handoff: { reason: 'Deck outline and organization preview are ready for verification.' },
    },
    {
      id: 'security_review',
      kind: 'agent_task',
      agentId: 'security_reviewer',
      title: 'Review office data exposure',
      instruction: 'Check the handoff for secret exposure, risky writes, and unsupported external calls.',
      expectedOutput: 'Security review result.',
      dependencies: ['verify_office_handoff'],
      handoff: { reason: 'Verified office handoff is ready for data exposure review.' },
    },
    { id: 'synthesize', kind: 'synthesis', dependencies: ['security_review'] },
    { id: 'final_verification', kind: 'verification', dependencies: ['synthesize'], minimumConfidence: 0.5 },
  ],
};
