import type { OrchestrationRecipe } from '../workflow-types.js';

export const pptFromFolderRecipe: OrchestrationRecipe = {
  id: 'ppt-from-folder',
  displayName: 'Folder to presentation outline',
  mode: 'handoff',
  agents: ['researcher', 'writer', 'ppt_designer', 'verifier', 'security_reviewer'],
  steps: [
    {
      id: 'map_folder_sources',
      kind: 'agent_task',
      agentId: 'researcher',
      title: 'Map folder source evidence',
      instruction: 'Search the supplied folder context and extract bounded source evidence for a presentation.',
      expectedOutput: 'Evidence map grouped by topic, source file, and presentation relevance.',
      handoff: { reason: 'Supervisor assigns folder evidence mapping before story drafting.' },
    },
    {
      id: 'draft_storyline',
      kind: 'agent_task',
      agentId: 'writer',
      title: 'Draft presentation storyline',
      instruction: 'Turn the mapped evidence into a concise presentation storyline with key claims and gaps.',
      expectedOutput: 'Presentation storyline with claims, supporting evidence, and unresolved questions.',
      dependencies: ['map_folder_sources'],
      handoff: { reason: 'Mapped source evidence is ready for storyline drafting.' },
    },
    {
      id: 'outline_deck',
      kind: 'agent_task',
      agentId: 'ppt_designer',
      title: 'Create deck outline',
      instruction: 'Create a slide-by-slide deck outline from the storyline, including suggested visuals and speaker notes.',
      expectedOutput: 'Slide outline with titles, bullets, visual suggestions, and speaker notes.',
      dependencies: ['draft_storyline'],
      handoff: { reason: 'Storyline is ready for slide outline design.' },
    },
    {
      id: 'verify_deck_outline',
      kind: 'agent_task',
      agentId: 'verifier',
      title: 'Verify deck outline',
      instruction: 'Check that the deck outline is grounded in the source evidence and calls out missing data.',
      expectedOutput: 'Verification result with unsupported claims, missing evidence, and pass/fail.',
      dependencies: ['outline_deck'],
      handoff: { reason: 'Deck outline is ready for grounding verification.' },
    },
    {
      id: 'security_review',
      kind: 'agent_task',
      agentId: 'security_reviewer',
      title: 'Review presentation data exposure',
      instruction: 'Check the deck outline for secret exposure, risky writes, and unsupported external calls.',
      expectedOutput: 'Security review result for the proposed presentation output.',
      dependencies: ['verify_deck_outline'],
      handoff: { reason: 'Verified deck outline is ready for data exposure review.' },
    },
    { id: 'synthesize', kind: 'synthesis', dependencies: ['security_review'] },
    { id: 'final_verification', kind: 'verification', dependencies: ['synthesize'], minimumConfidence: 0.5 },
  ],
};
