export const RUNTIME_DEPENDENCY_CATALOG = Object.freeze([
  {
    id: 'node',
    section: 'A4',
    label: 'Node.js 运行时',
    description: '随应用提供的本地 Node 执行环境，用于启动 host 与内置脚本。',
    required: true,
    installMode: 'bundled',
    estimatedDownloadBytes: 0,
  },
  {
    id: 'webview2',
    section: 'A1',
    label: 'Microsoft Edge WebView2',
    description: 'Windows 桌面外壳渲染界面所需的系统运行时。',
    required: true,
    installMode: 'system',
    estimatedDownloadBytes: 0,
  },
  {
    id: 'python-embedded',
    section: 'A2',
    label: '内置 Python',
    description: '随包提供的 Python 环境，用于可选数据处理与脚本能力。',
    required: true,
    installMode: 'bundled',
    estimatedDownloadBytes: 0,
  },
  {
    id: 'cjk-fonts', section: 'A3', label: '中日韩字体包',
    description: '确保中文、日文、韩文内容在安装版中正常显示。',
    required: true, installMode: 'bundled', estimatedDownloadBytes: 0,
  },
  {
    id: 'vc-runtime',
    section: 'A5',
    label: 'Visual C++ 运行库',
    description: 'Windows 原生依赖所需的 VC++ 运行库。',
    required: true,
    installMode: 'system',
    estimatedDownloadBytes: 0,
  },
  {
    id: 'sqlite',
    section: 'F2',
    label: 'SQLite 存储运行时',
    description: '用于本地会话、记录与轻量索引存储。',
    required: true,
    installMode: 'bundled',
    estimatedDownloadBytes: 0,
  },
  {
    id: 'proxy', section: 'F1', label: '网络代理配置',
    description: '读取系统或环境代理，用于模型调用和连接器访问外网。',
    required: false, installMode: 'environment', estimatedDownloadBytes: 0,
  },
  {
    id: 'data-science',
    section: 'B1',
    label: '数据分析组件',
    description: '按需安装的 Python 数据处理依赖，用于表格、统计和分析工作流。',
    required: false,
    installMode: 'on-demand',
    estimatedDownloadBytes: 200 * 1024 * 1024,
    sourceKind: 'official',
    sourceUrl: null,
    sha256: null,
    signaturePolicy: 'sha256-required',
    cleanup: { relativePath: 'components/data-science' },
  },
  {
    id: 'playwright-chromium',
    section: 'B2',
    label: '浏览器自动化组件',
    description: '按需安装 Chromium 浏览器，用于网页自动化和截图验收。',
    required: false,
    installMode: 'on-demand',
    estimatedDownloadBytes: 150 * 1024 * 1024,
    sourceKind: 'official',
    sourceUrl: null,
    sha256: null,
    signaturePolicy: 'sha256-required',
    cleanup: { relativePath: 'components/playwright-chromium' },
  },
  {
    id: 'tesseract-ocr',
    section: 'B3',
    label: 'OCR 文字识别组件',
    description: '按需安装 OCR 引擎，用于图片和扫描件文字提取。',
    required: false,
    installMode: 'on-demand',
    estimatedDownloadBytes: 120 * 1024 * 1024,
    sourceKind: 'official',
    sourceUrl: null,
    sha256: null,
    signaturePolicy: 'sha256-required',
    cleanup: { relativePath: 'components/tesseract-ocr' },
  },
  {
    id: 'pandoc',
    section: 'B4',
    label: '文档转换组件',
    description: '按需安装 Pandoc，用于 Office、Markdown 等文档转换链路。',
    required: false,
    installMode: 'on-demand',
    estimatedDownloadBytes: 80 * 1024 * 1024,
    sourceKind: 'official',
    sourceUrl: null,
    sha256: null,
    signaturePolicy: 'sha256-required',
    cleanup: { relativePath: 'components/pandoc' },
  },
  {
    id: 'ffmpeg',
    section: 'B5',
    label: '音视频处理组件',
    description: '按需安装便携版 ffmpeg，用于未来音视频处理技能。',
    required: false, installMode: 'on-demand', estimatedDownloadBytes: 100 * 1024 * 1024,
    sourceKind: 'official',
    sourceUrl: null,
    sha256: null,
    signaturePolicy: 'sha256-required',
    cleanup: { relativePath: 'components/ffmpeg' },
  },
  {
    id: 'mingit', section: 'B6', label: 'Git 轻量运行时',
    description: '按需安装 MinGit，用于仓库连接器和本地版本控制操作。',
    required: false, installMode: 'on-demand', estimatedDownloadBytes: 80 * 1024 * 1024,
    sourceKind: 'official',
    sourceUrl: null,
    sha256: null,
    signaturePolicy: 'sha256-required',
    cleanup: { relativePath: 'components/mingit' },
  },
  {
    id: 'sandbox-isolation',
    section: 'C1',
    label: '沙箱隔离运行时',
    description: '使用 WSL2 或 Docker 为工具执行提供网络和文件隔离。',
    required: false,
    installMode: 'system',
    estimatedDownloadBytes: 0,
  },
]);
